### ISSUE TITLE
broken link to the map

### ISSUE THREAD

**Issue by agricolamz** [vasishth/smlp2019#1]
Hi,

the map link that you provided is broken.

https://www.uni-potsdam.de/db/zeik-portal/gm/griebnitzsee.pdf

**Comment by vasishth** [comment]
Sorry, it seems that map has disappeared. But I did put up another link earlier, and that seems to work. Can you check? Here is the link: https://www.uni-potsdam.de/db/zeik-portal/gm/lageplan-up.php?komplex=3

**Comment by agricolamz** [comment]
thx! this one works!
